### ISSUE TITLE
Questions on Pause and USB Drives

### ISSUE THREAD

**Issue by ClaudeVernier** [ms-iot/UniversalMediaEngine#10]
Hello, 

Thank you for this project, I am using it in a first project with IoT and RPi3, 
it is an MP3 Alarm clock for my kids. I am using VS2015 and C#. 

I would like to ask two questions, if you could have a minute to spare and provide some guidance, it would help me !

1) Pause
When I use the Pause() method, it stops the music but to get the music again, I need to use again  the Play("C:\\Data\\Users\\DefaultAccount\\AppData\\Local\\...\\Music\\TestsSong.mp3") method which starts the song back from the beginning, I was expecting that using Pause() again would continue the song, is it me that used it wrong ?  Is it implemented already and I would have missed it ?

2) USB Drive
My application first reads the file that I stored on local for tests and then reads the files from an USB Drive, when I use the Play("F:\\Girl\\Album1\\Song1.mp3") method with a path on the USB Drive, nothing happens, no error, no sound.  I did set capabilities and added MP3 as file type as I was able to read the name of the file but would there be something preventing your module to read the file ?

Thank you for any help you could provide.

Regards, 
Claude VERNIER

**Comment by saraclay** [comment]
Closing this out as it's been a while. Feel free to file an issue on ms-iot/content as we are more active there.
